# Generated by Django 5.1.3 on 2024-11-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
